indiana-university/rivet-source

- src/components/12-modals/modals.hbs
- src/js/components/modal.js
This PR should fix console errors when opening and closing the modal programmatically without the presence of a button/element with a `data-modal-trigger` attribute used to open the modal.
This was reported to me directly offline, so no issue currently exists. The errors do not break the functionality of the modal opening or closing, but to prevent the `customEvent`s from firing off.
All the modal tests are passing, and I tested locally opening and closing the modal without the presence of a trigger element i.e. using only the `.open()` and `.close()` methods.
After a review, I think it would be good to push this out as a minor/patch release.
> Fixed issue where modal open and close methods where throwing console errors when used with out a modal trigger button

- package.json
This release is the alpha for a patch for the modal where it was throwing errors when no modal trigger was present.
See #52 for more info
> Release 1.2.1-alpha

- src/sass/utilities/_utilities-spacing.scss
Can use `rvt-m-all-none`, `rvt-p-all-none`, or other spacing classes to remove padding or margins. From issue #24. Still need to edit the documentation to reflect this change.
> Added none alias to spacing classes

- src/components/100-utilities/config.yml
- src/components/100-utilities/utilities--flex.hbs
- src/components/100-utilities/utilities.config.yml
- src/sass/core/_variables.scss
- src/sass/rivet.scss
- src/sass/utilities/_utilities-display.scss
- src/sass/utilities/_utilities-flex.scss
This PR adds a new set of comprehensive flex utilities to help developers have more fine-grained control over layout. White the grid is good for overall page layout, things can get messy when trying to nest too many grids to achieve complex layouts.
This new set of flex utilities gives developers a set of CSS classes they can combine to create more complex responsive layouts at the component level.
This adds utility classes for all of the major flexbox properties that affect **flex containers**:
- `display`
- `flex-direction`
- `flex-wrap`
- `justify-content`
- `align-items`
- `align-content`
And some that apply to **flex items**:
- `flex-shrink`
- `flex-grow`
- `align-self`
Flex properties **not included** in these utilities (container and items):
- `flex-flow` - This container property …
> Added new flexbox utility classes

- src/sass/utilities/_utilities-flex.scss
This PR add the missing `.rvt-inline-flex` utility class that I forgot to add in #75 
I realized it was missing while updating the docs. I don't think we need to bother doing another release candidate for this. It will just go out with the final `1.3.0` release. I'll make sure the site includes docs for this new class.
> Added missing display property for inline-flex

- CONTRIBUTING.md
Now that all the information about contributing to Rivet [lives in the wiki](https://github.com/indiana-university/rivet-source/wiki), I've removed the redundant information from the `CONTRIBUTING.md` file and replaced it with links off to the wiki.
> Updated CONTRIBUTING.md file to point to wiki

- src/sass/utilities/_utilities-flex.scss
The copyright header for sass files is handled manually, and this one was missed previously. See issue #90.
> Added copyright header to flex sass file

- src/components/101-includes/includes--alert-close-button.hbs
- src/js/components/alert.js
Updated the dismiss button for alerts to allow usage of `[data-alert-close]` as an alternative option to `.rvt-alert__dismiss`. See issue #85.
> Added optional alert dismissal data selector

- src/sass/components/_buttons.scss
Removed unnecessary background-color property from active state for small buttons. See issue #102.
> Fixed active state background color for small secondary button

- README.md
Austin recently requested that we add badges similar to ones on other GitHub repos (see the [React repo](https://github.com/facebook/react/) for an example). In doing so, I also restructured the README to begin with the name 'Rivet', and moved other headings down in the hierarchy to reflect this.
> Added status/package badges to README

- src/sass/components/_breadcrumb.scss
- src/sass/components/_header.scss
- src/sass/components/_menu.scss
- src/sass/components/_modals.scss
- src/sass/components/_tabs.scss
- src/sass/core/_tools.scss
This pull request replaces remaining instances of the `bp()` Sass function with the appropriate `$breakpoint-*` variable. This should help make the Sass easier to read.
Fixes #115
> Replaced instances of bp() with the $breakpoint variable

- src/components/23-input-group/input-group.hbs
- src/sass/components/_input-group.scss
Fixed bug related to z-indexes of elements within input groups. For more information see issue #111.
> Updated focus for input groups

- src/components/04-list/list-definition/list-definition.config.yml
- src/components/04-list/list-ordered/list-ordered.config.yml
- src/components/04-list/list-ordered/list-ordered.njk
- src/components/04-list/list-plain-text/list-plain-text.config.yml
- src/components/04-list/list-plain-text/list-plain-text.njk
- src/components/04-list/list-unordered/list-unordered.config.yml
- src/components/04-list/list-unordered/list-unordered.njk
- src/components/components.config.yml
This moves global data that can be used across components and variants into the `components.config.yml` file. An example that's used within the `list` component:
```
list_items:
- List Item One
- List Item Two
- List Item Three
- List Item Four
```
Other related fixes:
- Adjusted indentation inside components.config.yml.
- Removed 'collated: true' from list component variants since it's not needed in this case.
> Moved global data into components.config.yml

- package-lock.json
- package.json
This updates the version of Fractal from `1.1.7` to `stable.beta.2` as a workaround for this error: https://github.com/frctl/nunjucks/issues/5, which was fixed here: https://github.com/frctl/fractal/pull/472. The error was occurring when saving templates using the extension `render` from the Fractal Nunjucks Adapter.
> Changed Fractal version to stable.beta.2

- src/components/07-radio-input/radio-input.config.yml
- src/sass/components/_radios.scss
In this PR:
- Adds a "disabled-checked" variant to the `radio-input.config.yml` to test for radio inputs that are both disabled and checked.
- Increases the background-color from `$color-black-300` to `$color-black-600` for radio inputs that are both disabled and checked.
See issue #101.
> Darkened background on disabled checked radio inputs

- src/sass/components/_box.scss
This fix extends `border-top: none` to include all rows within the box component, not just those rows within the card variant as before. For instances where there isn't a header preceding the first row, `.rvt-box` still provides a border-top.
See issue #133.
> Removed border-top for first-child of rows within a box

- src/js/components/dropdown.js
- Adds a selector of :not([disabled]) to each of the dropdown toggle
variables to prevent disabled buttons from opening/toggling when 
clicked or activated via keyboard.
- Fixes a couple typos.
See issue #125.
> Fixed dropdown toggling when disabled issue

- src/sass/components/_loading-indicator.scss
In this PR:
- Refactored the loading indicator to recalculate the `border-width` based on the width being used (this is based on the understanding that at `16px` or `1rem` the border should be `2px` or `.125rem`
- Calculated border widths:
- `xxs`: 2px
- `xs`: 2.5px
- `sm`: 3.5px
- `md`: 4px
- `lg`: 5.5px
- `xl`: 6.5px
- `xxl`: 8px
For more details, see issue #131.
> Updated loading indicator to calculate the appropriate border-width

- src/js/components/modal.js
When initially opening a modal, if the user presses shift + tab, the focus leaves the modal. This fix sets the focus to the first focusable element within the modal when shift + tab is pressed upon first opening the modal.
For more details, see issue #13.
> Fixed backward tabbing issue for modals

- src/js/components/modal.js
Removed `else` statement because it included the same logic as the first `if` statement and moved the `else` statement's condition into the `if` statement.
> Refactored _handleBackwardTab function

- src/components/includes/includes--trident.njk
In `includes--trident.njk`, the `aria-describedby` on the `svg` element was removed and `aria-hidden="true"` was added.
See issue #200 for more details.
> Replaced aria-describedby with aria-hidden

- .circleci/config.yml
In this PR:
- Created filter for `2.0.0-dev` and `2.0.0-master` branches in CircleCI
- Applied filter to `build` job in CircleCI workflow
What this doesn't do:
- This does not filter out feature branches intended for inclusion in `v2` branches
> Created filter for v2 dev and master branches

- gulpfile.js
The bamboo build has been breaking. It seems that I removed the build task from the Gulpfile when I rewrote everything. It's not used in the npm scripts, so I probably missed that it was being used by Bamboo.
> Reintegrated gulp build task

- .eslintrc.js
The ecmaVersion value was set to '2018' within the eslint config to prevent errors when the spread operator is used within an object.
**Example:**
```
const settings = {
...defaultOptions,
...options
};
```
Setting `"experimentalObjectRestSpread": true` was a previous solution to allow spread operators within objects, but that has been deprecated in favor of `"ecmaVersion": 2018`.
https://eslint.org/docs/user-guide/migrating-to-5.0.0#-the-experimentalobjectrestspread-option-has-been-deprecated
> Set ecmaVersion to 2018 in .eslintrc.js

- src/sass/components/_menu.scss
I noticed that the CSS for the Menu component was broken. Looks like this snuck through in #212 This should fix that up.
> Fixed broken prefix variable

- src/components/utilities/utilities.config.yml
- src/sass/components/_alerts.scss
- src/sass/components/_badges.scss
- src/sass/components/_box.scss
- src/sass/components/_breadcrumb.scss
- src/sass/components/_buttons.scss
- src/sass/components/_checkboxes.scss
- src/sass/components/_dropdown.scss
- src/sass/components/_feature.scss
- src/sass/components/_file-input.scss
- src/sass/components/_footer.scss
- src/sass/components/_header.scss
- src/sass/components/_input-group.scss
- src/sass/components/_inputs.scss
- src/sass/components/_links.scss
- src/sass/components/_loading-indicator.scss
- src/sass/components/_menu.scss
- src/sass/components/_modals.scss
- src/sass/components/_pagination.scss
- src/sass/components/_radios.scss
- src/sass/components/_sidenav.scss
- src/sass/components/_step-indicator.scss
- src/sass/components/_tables.scss
- src/sass/components/_tabs.scss
- src/sass/components/_timeline.scss
- src/sass/components/_validation.scss
- src/sass/core/_base.scss
- src/sass/core/_variables.scss
- src/sass/utilities/_utilities-border.scss
In this PR:
- Changed double dashes (`color-black--100`) to single dashes (`color-black-100`)
- Changed `050` base value to `000` (`color-black-050` changes to `color-black-000`)
- Fixed incorrect hexadecimal values in the yellow color scale
See issue #234 for more details.
> Update color scale naming conventions

- .github/workflows/nodeCI.yml
- package-lock.json
- package.json
In this PR:
- Added workflow that (once incorporated) builds and tests new branches from the `2.0.0-dev` branch
- Updated version of `node-sass` package being used (old version couldn't run on node 12.x)
- Ran `npm run audit` and subsequently `npm audit fix` to update a few deep dependencies
> Created build/test workflow for repo

- .github/workflows/alpha.yml
- package-lock.json
- package.json
In this PR:
- Created `.github/workflows/alpha.yml` for handling the publishing of alpha packages
- Updated package name to reflect preferred npm repo for 2.0.0+
> Added workflow for publishing packages to the alpha tag

- src/components/file-input/file-input.config.yml
- src/components/file-input/file-input.njk
- src/js/components/fileInput.js
- src/js/index.js
This one isn't quite ready to be merged in, but I would still like some initial feedback on it. I'm mainly looking for feedback about:
- where to place the custom events - I can see value for developers to have a custom event fire _before_ and _after_ the file upload change even happens, since there will be different data for each. So, should it be placed at the beginning or end of the "build" methods, or maybe both?
- whether the `_handleChange` method needs to be broken down further to other methods for better readability and organization
- how we can best provide the ability to completely disabling the file input event using a custom event, similar to `event.preventDefault()` in other components. Without any JavaScript, the browser's file selection modal still appears when the matching …
> Refactored file input component

- package.json
Ok, for real this time. This PR will release the first early alpha of Rivet 2. As we move to 2.0.0 we'll be publishing to a new npm repository named `rivet-core`. We'll make sure to highlight this in any migration guides/docs.
This release includes:
- New _Sidenav_ component
- New _Action_ component
- New _Feature_ component
- Revised black color scale
- Update to Sass color variable names e.g. `$color-black--050` becomes `$color-black-000` and color scales now begin at `-000` instead of `--050`. [See this PR for more detail](https://github.com/indiana-university/rivet-source/pull/236)
- Refactored the Alert component
> Alpha Release 2.0.0-alpha

- src/components/example-layouts/example-layouts--wysiwyg.njk
- src/sass/rivet.scss
- src/sass/utilities/_utilities-wysiwyg.scss
In this PR:
- Adds CSS namespacing class `rvt-wysiwyg` for handling extra code created by a WYSIWYG
- Uses the "lobotomized owl selector" (https://alistapart.com/article/axiomatic-css-and-lobotomized-owls/) to set a base `margin-top` value for all sibling elements
- Sets all empty elements to `display: none`. This includes `<br />`, since it is technically an empty element.
- Zeroes out the `margin-top` for multiple `code` elements within a paragraph (or within other inline elements) because the `code` element is `display: inline-block`
- Paragraphs including a non-breaking space `&nbsp;` are not being overridden, nor are paragraphs with only white space. If we choose to override these, we'll have to include some JavaScript to target those contents.
> Added CSS namespacing for wysiwyg sections

- cypress/integration/dropdown_spec.js
- src/components/dropdown/dropdown.config.yml
- src/components/dropdown/dropdown.njk
- src/js/components/dropdown.js
- src/js/index.js
- src/js/utilities/keyCodes.js
**In this PR:**
- Refactored component JS to ES6
- Set eventListener to the `document` so multiple instances of the dropdown can be managed within a page
- Close all other dropdowns when a new one is opened
- Added option to enable/disable "prevent page scroll" when the up and down arrows are pressed
**Development checklist:**
> Refactored dropdown JS

- src/components/dropdown/dropdown.njk
- src/js/components/dropdown.js
In this PR:
- Added `dropdownOpen` and `dropdownClose` customEvents
- Added logic for `open()` and `close()` to execute on only one targeted dropdown at a time. This will prevent `close()` from getting fired multiple times on dropdowns that are already closed.
- Refactored logic for the `esc` keyboard functionality
> Added customEvents to dropdown component

- .github/workflows/alpha.yml
- .github/workflows/test-build.yml
In this PR:
- Added alpha release workflow for GitHub actions
- Refactored `nodeCI.yml` and renamed to `test-build.yml`
**Notes about the alpha release workflow:**
- The workflow begins when a tag including `v**-alpha**` has been pushed
- Once started, it tests the build, publishes the package to npmjs.com, and then creates a release
- When the release is created, it is set up as a `draft` and `prerelease` and a copy of the build (`rivet.zip`) is attached
Thanks to @illusivesunrae for helping me work through this!
See issue #247 for more details.
> Added alpha release workflow

- gulpfile.js
- package.json
- src/js/index.js
In this PR:
- Set sources in `distJS` task to be explicit files, rather than all of the files in the `static/js` directory
- Reordered `gulp` JS tasks to reflect build processes
- Renamed JS compiling/transpiling tasks to `compileIIFE()` and `compileESM()`
- Updated `index.js` to export components separately, instead of within one `default`
- Added `main` and `module` values to `package.json`
See #254 for more details.
Thanks to @illusivesunrae for helping me differentiate between the different JS build processes in the `gulpfile.js`.
> Refactored IIFE/ESM module transpiling process

- src/components/sidenav/sidenav.njk
- src/sass/components/_sidenav.scss
If the link label was longer than the container, the button would wrap to the next line along with the text.
This fix adds a `div` around the `rvt-sidenav__link` and `rvt-sidenav__toggle` to contain them to one line and prevent wrapping.
The Sass `@each` loop was also updated to reflect this new markup structure.
> Added fix for text improperly wrapping in sidenav

- src/sass/components/_sidenav.scss
This hides the Sidenav toggle buttons with `display: none` on page load, and then displays them with `display: block` once JavaScript has been loaded. This will prevent the buttons from displaying if JavaScript fails to load on the page.
> Added CSS to display buttons if JS loads

- src/js/components/sidenav.js
In this PR:
- The `addEventListener` was moved to the beginning of the `init()` so it's run before any `return`s are called
- Logic for `this.openAllOnInit` was moved up front so the rest of the code can be skipped if it's enabled
- Added logic to handle toggle/menu pairs whenever a toggle is set to `aria-expanded="true"` in the markup before any JS is run. Any toggle that has `aria-expanded="true"` added in the markup will initialize opened on page load, and the rest will remain closed.
It would be good to have some feedback on this line in `sidenav.js`–
`childMenus.forEach(childMenu => childMenu.setAttribute('hidden', ''));`
–since this is closing all of the childMenus, and then later on some might be getting re-opened if the toggle is set to open within the markup.
> Added logic for folds expanded in markup

- .eslintignore
Reference to `js/` in `.eslintignore` was targeting `src/js/`
> Fixed .eslintignore syntax

- .github/workflows/alpha.yml
- .github/workflows/test-build.yml
This PR updates the OS for the two workflows from `ubuntu-latest` to `ubuntu-16.04`. This is a fix for an issue within the `test-build` workflow where Cypress was failing to start.
The Cypress GH Action readme details this fix to the issue here: https://github.com/cypress-io/github-action#important
> We are getting reports that Cypress has suddenly started crashing when running on ubuntu-latest OS. Seems, GH Actions have switched from 16.04 to 18.04 overnight, and are having a xvfb issue. Please work around this problem by using runs-on: ubuntu-16.04 image.
> Set OS to Ubuntu 16.04 for GH Actions workflows

- gulpfile.js
- src/js/components/accordion.js
In this PR:
- Added new task `setProdNodeEnv` to set `process.env.NODE_ENV` to `production`
- Added the `setProdNodeEnv` task to the `release` and `build` exports
- Added logic to set different options within `eslint()` if the `setProdNodeEnv` has been run (ex: `throwOnError: true`)
> Added logic to change eslint options based on environment when compiling

- src/js/components/accordion.js
- src/sass/components/_accordion.scss
- src/sass/components/_alerts.scss
- src/sass/components/_dropdown.scss
- src/sass/components/_inputs.scss
- src/sass/components/_sidenav.scss
- src/sass/components/_tables.scss
- src/sass/components/_tabs.scss
- src/sass/core/_base.scss
- src/sass/rivet.scss
In this PR:
`libs/normalize` in `rivet.scss` has been commented out to disable all `normalize.css` styles. To test out the differences with or without normalize.css, this line can be uncommented and commented to enable and disable. Once everything looks good, this line and the `libs/_normalize.scss` file can be removed entirely.
- Set `font` on all elements to `inherit` (`_base.scss`)
- Set `button` margins to 0 to override Safari user agent stylesheet defaults (`_base.scss`)
- Added `-moz-focus-inner` to remove border on focused buttons within Firefox (`_base.scss`)
- Removed scrollbar from `textarea` in IE (`_inputs.scss`)
- Set `border-collapse` and `border-spacing` to match normalize (`_tables.scss`)
> Removed normalize.css

- src/components/_preview-no-padding.njk
- src/components/button/button/button.njk
- src/components/checkbox/checkbox.njk
- src/components/dropdown/dropdown.config.yml
- src/components/dropdown/dropdown.njk
- src/components/header/header.config.yml
- src/components/header/header.njk
- src/components/includes/includes--header-controls.njk
- src/components/modal/modal.njk
In this PR:
- Previously, the dropdowns weren't working in the header examples. If the inline `script` in the `dropdown.njk` file is wrapped with `window.addEventlistener('load')`, this makes sure it runs after the Rivet IIFE has been loaded. Otherwise, it runs too soon, `Rivet is not defined` is logged to the console, and the component fails to have its event listener added.
- Changed instances of `sr-only` and `v-hide` classes to `rvt-sr-only` to hide screenreader only text (examples: close icon and drawer icon buttons)
- Indented YAML contents for `dropdown.config.yml` and `header.config.yml`
> Fixed broken dropdowns and icon text in header examples

- gulpfile.js
- package-lock.json
- package.json
Removed `gulp-uglify` in favor of `gulp-terser` due to issues handling ES6 modules.
> Updated gulp js minification

- src/js/index.js
This PR changes the exports within `src/index.js` from `default` back to named exports. This had been previously fixed but was overridden by another commit or merge.
See this issue for more details: #299
> Updated src/index.js to named exports

- src/components/avatar/avatar.config.yml
- src/components/avatar/avatar.njk
- src/components/example-layouts/example-layouts--avatar-responsive.njk
- src/components/example-layouts/example-layouts--avatar.njk
- src/sass/avatar/_base.scss
- src/sass/avatar/_index.scss
- src/sass/rivet.scss
In this PR:
- Created nunjucks template, config.yml for settings, and a blank README for docs
- Set up component variants based on this prototype: https://codepen.io/levimcg/pen/ZEGbMgw
- Added the `xs` variant and set the "regular" option to default to the `sm` variant so that if no modifier class is set, then the avatar will default to the `sm` variant
- Added responsive classes for different breakpoints. This required adding two Sass maps that could potentially be refactored as design tokens, if needed.
- Added an example layout of the text and image avatars displaying on a dark background
> Created avatar component

- .github/workflows/alpha.yml
- gulpfile.js
- package.json
This fixes an issue caused by `rivet.zip` file being present in our `.gitignore`, which resulted in it being unreachable by the `upload-release-asset` action. To fix this, we created a new script in `package.json` to create a renamed asset for upload to GitHub for release.
> Created script for uploading release asset

- src/components/quote/quote.config.yml
- src/components/quote/quote.njk
- src/sass/quote/_base.scss
- src/sass/quote/_index.scss
- src/sass/rivet.scss
In this PR:
This component was created using [this prototype](https://codepen.io/levimcg/pen/BaNoOGZ) as a base example. There are only three main parts: the decorative double-quote pseudoelement, the quote, and the author, so there currently aren't any other variants to test or review.
- The example has been checked to make sure all of the text is passing color contrast requirements for accessibility.
- The `preview` property was set to the `preview-no-padding` template to make it easier to review the component.
> Created quote component

- src/components/avatar/avatar.njk
- src/components/quote/quote.config.yml
- src/components/quote/quote.njk
- src/sass/quote/_base.scss
In this PR:
- Text and image `avatar` variants in different sizes were added as options for the `quote` component
- A `utility_class` option was added to the `avatar` component so a utility like `rvt-m-right-md` could be added to the `avatar` within the quote component
> Added avatar variants to quote component

- .github/workflows/alpha.yml
- gh-actions/build-changelog/action.yml
- gh-actions/build-changelog/index.js
- package-lock.json
- package.json
Earlier this week, @illusivesunrae and I worked on adding a GitHub action for automatically creating a changelog and adding it to the release whenever a release workflow is ran. To avoid cluttering up the commit history with trial and error experimention, we worked through the process at this repo: https://github.com/zttodd/github-js-actions
@illusivesunrae did the large majority of this PR in figuring out the logic of how everything worked, and we both peer coded through troubleshooting and debugging the action during initial testing.
Here's what we have left to do:
- Test out how this action will work within the `alpha.yml` release as a local action without publishing to the GitHub action marketplace. I talked to @levimcg about this, and because it's just an `index.js`, `action.yml`, …
> Created action for automating the creation of changelogs

- src/components/modal/README.md
So this is definitely still a little rough. I would love feedback on the best syntax for listing the public methods now that we are using class instantiation. 
I did notice in the Aria authoring practices, it mentions that the modal container should have `aria-modal` set to `true`. This was introduced to replace `aria-hidden` for modals, but we are also not using that (we use `hidden` instead). We can decide if this is something we should create an issue for.
> Added documentation for modal

- src/components/dropdown/README.md
This PR adds a first draft of the docs for the `dropdown` component. One item to note is in the **labeling** section, there is an _optional_ `aria-controls` that can be added. We haven't included that within our Fractal/Nunjucks template, so I wanted to make sure that this was something we still wanted to include within the docs, and if so whether we should add it into the Nunjucks template.
I borrowed the table layout and language from #357 for the **"public" methods** and **custom events** sections.
> Added documentation for dropdown

- src/components/link/README.md
This PR migrates the `link` docs, adds a markup section, and reworks the "Microcopy & accessibility notes" into "accessibility requirements" and "implementation notes".
> Migrated documentation for link component

- src/components/utilities/README.md
In this PR:
The docs for `display` utility classes were migrated from [rivet.iu.edu](https://rivet.iu.edu). These were added to the README.md within the `utilities` folder. I've set it up so that each utility can be separated by a horizontal rule (`---`), but if the file begins to get too lengthy then we can consider other options.
Docs for `rvt-display-none` were also added as well. See this issue for more details: #291
> Migrated display utility docs and added rvt-display-none

- src/components/box/README.md
This was a fairly standard migration.
@illusivesunrae  when you're back, let's talk about how to write the docs for when to use/not use the box.
> Migrated documentation for the box component

- src/sass/header-system/_header-local.scss
This issue has come up on a couple sites using the prototype version of the header system. I just got another report of the issue and realized that we hadn't fixed it here in the codebase. Wanted to get this in before we finish up the next alpha release.
Issue was being caused by the `flex-shrink` property defaulting to `shrink` which caused the svg icon inside the toggle button not to appear on iOS Safari. I tested in iOS locally. Can confirm this fixes the issue.
> Header system local module nav toggle fix

- src/sass/components/_buttons.scss
Documentation needs to be updated to say that XXS indicator is the only size you can use in small buttons.
Fixes #391
> Updated loading indicator margin to center XXS indicator in small button

- src/components/_preview-no-padding.njk
- src/components/breadcrumb/breadcrumb.config.yml
- src/components/breadcrumb/breadcrumb.njk
- src/components/layouts/01-index-summary-page.njk
- src/components/layouts/02-details-page.njk
- src/components/layouts/02-generic-details-page.njk
- src/components/layouts/03-gener-details-single-column.njk
- src/components/layouts/README.md
- src/components/layouts/_page-intro-partial.njk
- src/components/layouts/_prose-placeholder-partial.njk
- src/components/layouts/layouts.config.yml
- src/components/sidenav/sidenav.njk
- src/sass/breadcrumb/_base.scss
- src/sass/defaults/_reset.scss
- src/sass/grid/_base.scss
- src/sass/layout/_base.scss
- src/sass/layout/_index.scss
- src/sass/rivet.scss
- src/sass/utilities/_flow.scss
- src/sass/utilities/_index.scss
- src/sass/utilities/_prose.scss
This PR adds the basic shell for the the "details" layout. This will be the basis for a handful of other more specific layouts like a people profiles and articles. I wanted to break this up into a bit smaller PRs, so this only implements the basics. We can tackle more specific layouts like the person profile, and new/blog post in additional PRs.
- Implemented a base layout element creates a basic `rvt-layout` shell. This will be the basis from which we build additional layouts.
- The `rvt-layout` class is applied to the `body` and the child `rvt-layout__wrapper` class is applied to the `main` element. In this most simple form it creates a layout that pushes the footer to the bottom of the viewport if there is not enough page content to do so.
- Additional layout elements/CSS classes …
> Added basic details two-column page layout

- src/js/components/sidenav.js
You used to have to pass the entire toggle element to `open`/`close` fetched via `querySelector`. This PR changes the sidenav API where you now only have to pass the toggle element ID. This will make client code simpler.
- `open(toggleId)`
- `close(toggleId)`
There's some refactoring we'll need to do in the near future to reduce some duplication in the sidenav source file.
> Updated sidenav API to accept toggle ID rather than element

- src/components/sidenav/sidenav.njk
- src/sass/sidenav/_base.scss
Links that are in nested menus were shifting based on margin applied to links with the `aria-current` attribute. This pr reworks the way current states are displayed in the Sidenav to use the `::before` pseudo element instead of an inset box shadow.
> Fixed issue where Sidenav current indicator was causing links to shift on nested lists of links

- src/components/tabs/README.md
- src/js/components/accordion.js
- src/js/components/tabs.js
This PR updates the accordion and tabs APIs to accept a panel ID string instead of the target panel element in `open()`, `close()`, and `activateTab()`. This brings these components in line with how the sidenav API is set up.
I haven't done any code cleanup or refactoring -- this PR just includes the bare minimum to get the new API to function. I'll come back and clean up the component source files in a later PR.
> Updated accordion and tabs APIs to accept panel ID instead of element

- cypress/integration/accordion_spec.js
- cypress/integration/modal_spec.js
- cypress/integration/tabs_spec.js
This PR adds integration tests for the following component API methods:
- `Accordion.open()`
- `Accordion.close()`
- `Modal.focusTrigger()`
- `Modal.focusModal()`
- `Tabs.activateTab()`
> Added missing integration tests for component API methods

- src/sass/layout/_base.scss
This is a small fix that we've implemented as a patch once we noticed it using `2.0.0-alpha.5` on the v2 docs site.
> Fixed issue where non-breaking content cause main content area to overflow

- src/js/components/accordion.js
- src/js/components/alert.js
- src/js/components/component.js
- src/js/components/disclosure.js
- src/js/components/dropdown.js
- src/js/components/fileInput.js
- src/js/components/modal.js
- src/js/components/sidenav.js
- src/js/components/tabs.js
This PR updates the API for component custom events in the following ways:
- Event names are all past tense, i.e. `dropdownOpened`, `modalClosed`
- The value of the `event.target` property is always the emitting component's root DOM element
- The value of the `event.detail` property object only contains additional context about the event when needed, such as which tab was activated. References to relevant DOM elements are passed rather than ID strings.
> Updated component custom events API

- src/sass/checkboxes/_base.scss
Rounded corners in Firefox causes background colors to bleed through at the corners, when using box-shadow. Replacing the box-shadow border with a literal border fixes this. Works in Chrome, Safari, and Firefox. Also, did some other cleanup.
> Fix checkbox rendering in Firefox

- src/components/checkbox/README.md
- src/components/checkbox/checkbox.njk
- src/sass/checkboxes/_base.scss
Summary:
1. Replace `rvt-plain-list rvt-flex` example with `rvt-inline-list`.
2. Enforce line-height for checkbox labels, so the effective height is 24px.
3. Enforce the description element to be styled as a block, in case the markup is not a `<div>`.
4. Update all examples to use `<div>` over `<span>`.
> Enforce checkbox block styling in CSS, HTML, and examples

- src/sass/lists/_base.scss
Notes:
1. The inline list implementation is replaced with flex.
2. List items no longer set a line height or font size.
3. Inline list item margins are reset only on direct children, in case there would be some odd case in which you have nested lists under an inline list.
4. Spacing is managed by the [gap property](https://developer.mozilla.org/en-US/docs/Web/CSS/gap), which has [good browser support](https://caniuse.com/flexbox-gap), outside of IE.
5. Top margin is included on inline lists to maintain current spacing expectations (top margins on list items). This could be adjusted, if such spacing is reviewed for all list styles.
6. Removed the Sass mixin, to keep the code simpler and remove unintended classes (`.plain-list`, `.inline-list`).
> Use flex for inline lists

- src/sass/inputs/_base.scss
Updating the input background color to white ensures that inputs retain good contrast against contextual color. Also, if an input is placed on a light gray background, it makes it so the inputs don't accidentally look disabled.
> Update input background color to white

- src/components/01-utilities/text.njk
- src/sass/quote/_base.scss
- src/sass/utilities/_text.scss
- src/tokens/fonts.json
@scottanthonymurray FYI, this was a pretty minor update, but now we have proper design tokens and variables for font family since we're now including Georgia Pro for marketing site.
> Added new sans and serif design tokens for fonts

- src/js/components/tabs.js
Rivet v2 documentation will need to be updated to reflect this change.
> Removed up and down arrow key handlers from tabs component

- src/sass/link-hub/_base.scss
I just caught that I used the old blue color scale for the arrow inline svg background image. This PR updates to the correct color value.
> Updated link hub icon color to use correct color scale

- src/sass/defaults/_reset.scss
- src/sass/layout/_base.scss
This replaces the `width: 100%` style declaration for all Rivet images.
https://app.asana.com/0/1199946964816580/1201839449092957/f
Note that this change caused images in the Details layout breakout elements to not fill the width of their container. This PR adds a `width: 100%` style declaration to `img` elements within `rvt-layout__break-out` containers.
> Set default image style to max-width: 100%

- .github/workflows/beta.yml
Updating since Node.js version 12 reaches end of life on April 30, 2022.
> Updated beta workflow node version to 14

- package-lock.json
- package.json
This PR updates the build process to use the platform-agnostic `rimraf` command instead of `rm -rf`.
You'll need to run `npm i` to install the `rimraf` package before running the build process.
> Updated build process to use rimraf

- src/components/disclosure/disclosure.njk
- src/js/components/disclosure.js
This PR adds support for an optional `data-rvt-close-click-outside` attribute that can be added to a disclosure component's root element.
If present, the disclosure will close itself if the user clicks anywhere outside the disclosure element.
The dropdown and modal have similar functionality, but implemented slightly differently due to the unique nature of both components. I'll attempt to DRY this out a little in a separate PR.
> Added optional data-rvt-close-click-outside attribute to disclosure

- src/components/disclosure/disclosure.njk
- src/js/components/disclosure.js
This PR implements the missing `data-rvt-disclosure-open-on-init` attribute for the disclosure component.
This attribute was listed in the documentation but never implemented.
> Implemented data-rvt-disclosure-open-on-init attribute

- src/components/examples/examples--feedback-form.njk
- src/components/examples/examples--personal-details-form.njk
- src/sass/alerts/_base.scss
- src/sass/checkboxes/_base.scss
- src/sass/defaults/_reset.scss
- src/sass/file-input/_base.scss
- src/sass/hero-area/_base.scss
- src/sass/inputs/_base.scss
- src/sass/radios/_base.scss
- src/sass/stat/_base.scss
- src/sass/tables/_base.scss
- src/sass/utilities/_prose.scss
- src/sass/utilities/_text.scss
- src/tokens/line-heights.json
This PR adds the following line-height tokens and utility classes:
- `$line-height-tight` / `.rvt-lh-tight`: `1.2`
- `$line-height-base` / `.rvt-lh-base`: `1.5`
- `$line-height-loose` / `.rvt-lh-loose`: `1.65`
The `.rvt-lh-title` class remains for backwards compatibility.
> Added line-height tokens and utility classes

- src/js/components/modal.js
This PR fixes an error in the modal component JS that prevented the `data-rvt-modal-dialog` attribute from working properly.
> Fixed code error preventing modal dialog functionality from working

- src/js/components/dropdown.js
The up key handler already calls `event.preventDefault()`.
> Added missing event.preventDefault() call to dropdown down key handler

- cypress/integration/accordion_spec.js
- cypress/integration/alert_spec.js
- cypress/integration/dialog_spec.js
- cypress/integration/disclosure_spec.js
- cypress/integration/dropdown_spec.js
- cypress/integration/sidenav_spec.js
- cypress/integration/tabs_spec.js
- src/components/accordion/README.md
- src/components/disclosure/disclosure.njk
- src/js/components/accordion.js
- src/js/components/alert.js
- src/js/components/component.js
- src/js/components/dialog.js
- src/js/components/disclosure.js
- src/js/components/dropdown.js
- src/js/components/fileInput.js
- src/js/components/sidenav.js
- src/js/components/tabs.js
- src/sass/utilities/_prose.scss
This PR updates all custom event names to remove colons from the event name. This is a JavaScript API change that needed to be made before the production 2.0.0 release due to the potential for conflict with the way some JavaScript libraries like Vue.js attach event listeners directly in templates like `<div @rvtDisclosureOpened="someComponentMethod" />`. The colon could interfere with other conventions used like data binding via the `<div :class="someProperty" />` shorthand.
> Removed colon from CustomEvent names
