package.json, src/components/12-modals/modals.hbs, src/js/components/modal.js
This is the PR for the 1.2.1 release. I've tested the `1.2.1-alpha` and got the docs updated. We should be good to go.
=> Release 1.2.1

src/sass/utilities/_utilities-spacing.scss
This PR adds the responsive top/bottom left/right remove spacing utility classes that we accidentally omitted in #55
=> Added horizontal and vertical responsive remove utilities

src/components/22-dropdown/dropdown.hbs, src/js/components/dropdown.js
=> Replicated bug and added return statement to fix error.

src/js/components/tabs.js
=> Added class selector to aria-controls in order to fix specificity issue.

src/sass/components/_buttons.scss
Addresses https://github.com/indiana-university/rivet-source/issues/71
=> fix(Button): remove top and bottom padding on button element

.gitignore
This PR updates adds `.npmrc` and `.env` files to gitignore.
=> Adds config files to gitignore

package.json, src/sass/utilities/_utilities-display.scss
Getting this alpha/rc branch open. I'll be updating the docs over the next couple of days to prepare for the `1.3.0` release this coming Wednesday.
=> Release 1.3.0-alpha

src/components/14-footer/footer.hbs
This PR addresses issue #87. The copyright statement, privacy policy link, and accessibility link have been reordered and renamed to reflect new footer standards.
=> Updated footer to reflect changes to link order and link text

package-lock.json, src/sass/core/_variables.scss
=> Deprecated variable color-subtle-gray

package.json
Created prerelease for 1.4.0-alpha
=> Created prerelease for 1.4.0-alpha

src/sass/components/_footer.scss
=> Fixed breakpoints for new footer lockup

gulpfile.js, package-lock.json
This PR fixes issue where copyright banner was not being added to the compiled and minified Rivet css files. See issue #124 for more details.
=> Fixed broken headerCSS function

src/components/06-select-input/select-input.config.yml, src/components/06-select-input/select-input.hbs
In this PR:
- Updated functionality to pull appropriate inline alerts programmatically
- Refactored code to allow replacement options within other examples using an array (`options`)
=> Refactored select inputs in fractal

src/components/02-spacing/spacing.njk
@levimcg Same thing as #147. Unsure if this needs to have a component example in fractal?
=> Updated spacing file extension and reformatted syntax

src/components/14-footer/footer.njk
Incorrect indentation on a comment within the `footer.njk` file was also fixed.
=> Updated file extension for footer component

src/components/04-list/list-inline/list-inline.config.yml, src/components/04-list/list-inline/list-inline.njk
Adds the 'inline' list variant to the list component and updates the variables to use the global data in `components.config.yml`.
=> Added inline variant to list component

package-lock.json, package.json, src/components/05-text-input/text-input.config.yml, src/components/05-text-input/text-input.hbs, src/components/05-text-input/text-input.njk, src/components/11-alert/alert-inline/alert-inline.njk
Updated the file extensions to `.njk` and refactored the text-input and alert-inline components.
=> Refactored text-input

src/components/30-textarea/textarea.config.yml, src/components/30-textarea/textarea.hbs, src/components/30-textarea/textarea.njk
In this PR:
- Updated file extension to `.njk`
- Refactored component (very similar to text-input)
- Added message to render data (and corresponding `warning` context variable)
=> Updated file extension and refactored component

src/js/components/modal.js
In this PR:
- Renamed a function
- Added comments to denote the end of a deprecated section
=> Updated text within modal.js

src/components/sidenav/README.md
In this PR is a first draft of the docs for the Sidenav. Not currently included is the accessibility section, since we will need to evaluate how to best approach keyboard navigation for this component. Once that has been figured out, accessibility notes and implementation will be added to these docs.
This is my first doc for a component, so any and all feedback would be great! I mainly used the Menu component's docs as a baseline for comparison. Since the markup requirements are fairly rigid for this component to work correctly, I didn't include many notes about that, so feedback in that area would be great if necessary.
=> Added first draft of documentation for Sidenav

src/sass/components/_sidenav.scss
Fixes issue with wrapping text not indenting properly.
=> Changed text-indent to padding-left

src/components/avatar/README.md, src/components/avatar/avatar.njk, src/sass/avatar/_base.scss
In this PR:
- Added docs to `README.md` within the avatar component
- Added the class `rvt-avatar__image` to the `img` within the image avatar
- Updated the avatar Sass from `img` to `rvt-avatar__image`
=> Added docs for avatar component

src/components/action/README.md
In this PR:
- Created README.md for the action component and added documentation
=> Created basic documentation for the action component

src/components/grid/README.md
In this PR:
- created documentation for the grid
- drew from current documentation, where applicable
=> Created documentation for the grid component

.tokens.config.js, gulpfile.js, src/tokens/config/json.js, src/tokens/formats/json-formats.js
In this PR:
- Created new format for outputting design tokens as JSON
=> Created JSON design token output

src/components/quote/README.md
This PR updates the docs for the `quote` component based on the following comments in the closed PR #323
- https://github.com/indiana-university/rivet-source/pull/323#discussion_r387045892
- https://github.com/indiana-university/rivet-source/pull/323#discussion_r387048865
=> Updated quote docs based on feedback

src/components/file-input/README.md
This component adds the following sections to the `file input` component docs:
- When to use
- Adding the markup
- Initialization
- Accessibility requirement
It would be helpful to have some feedback on how to improve the Initialization section. I had a difficult time thinking of a standard way to recommend initializing, and explaining it a way that could be applied to each developer's unique scenario, and also not under-explaining it for people who don't have as much JavaScript experience.
I also wasn't sure of an instance where you wouldn't use a file input, since it seems to have one clear function, but I'm sure I'm missing some other instances where it might be misused.
=> Added documentation for the file input component

src/components/badge/README.md
This PR migrates the previous documentation for the badge component into Fractal.
=> Added documentation for badge

src/components/pagination/README.md
This PR migrates the docs for the paginations component, adds a markup section, and reorganizes and renames the sections.
=> Migrated documentation for pagination component

src/js/components/accordion.js
See issue #385 for more details.
=> Switched throw new TypeError for console.warn

src/sass/components/_buttons.scss, src/sass/components/_header.scss
=> Updated button focus outline color to match border/fill color

src/js/components/dropdown.js
=> Added toggle variable check to dropdown component JS

CONTRIBUTING.md, README.md
@levimcg Much of the information on setting up a local development environment has been moved here:
https://github.com/indiana-university/rivet-source/wiki/Pull-requests
=> Updated readme and contributing files for Q1 2021

cypress/integration/dropdown_spec.js, src/js/components/dropdown.js
Also updates the dropdown code to handle additional error states missed in PR #437 but revealed by the automated tests.
=> Added passing automated tests for calling API methods on removed dropdowns

.github/workflows/release-v1.yml, gh-actions/build-changelog/action.yml, gh-actions/build-changelog/index.js, gh-actions/get-package-version/action.yml, gh-actions/get-package-version/index.js, package-lock.json, package.json
@levimcg I _think_ this should be everything we need set up ahead of tomorrow's release.
=> Added GitHub workflow for v1.x.x releases

src/components/sidenav/sidenav.njk, src/sass/sidenav/_base.scss
Refactored sidenav component to use new styles from iu.edu project.
- Updated styles to match iu.edu implementation
- Removed logic for nesting background colors since the styles no longer call for it.
=> Sidenav refactor

package-lock.json, package.json
Uninstalled `pixelmatch` and `pngjs`.
Ran the test suite and confirmed no new issues cropped up as a result of uninstalling these libraries.
=> Removed unused visual regression testing packages and files

cypress/integration/modal_spec.js, package-lock.json, src/js/components/modal.js
=> Fixes error when Modal.open or Modal.close is called on a modal that has been removed from the DOM

src/components/table/table.njk, src/sass/components/_tables.scss
=> Fixed missing top border from .rvt-table-cells columns

src/components/examples/examples--media-object.njk, src/components/feature/basic/feature.config.yml, src/components/feature/feature-mods/feature-mods.config.yml, src/components/feature/feature-patterns/feature-patterns.config.yml, src/components/media-object/media-object.config.yml
This PR adds a depredated notice to components that have either been replaced, or are not longer relevant based on earlier pilot projects.
@scottanthonymurray Just a heads up. I've created internal tasks for updating docs, etc. for all of these.
=> Deprecated early alpha components

package-lock.json, src/js/components/tabs.js
Reverts indiana-university/rivet-source#522
=> Revert "Release 1.8.2"

package.json, src/js/components/tabs.js
Cleans up some release process typos.
=> Hotfix 1.8.2 cleanup

src/components/02-layouts/partials/_prose-placeholder-partial.njk, src/components/disclosure/README.md, src/components/disclosure/disclosure.njk, src/sass/disclosure/_base.scss, src/sass/disclosure/_index.scss, src/sass/rivet.scss
- Added basic styling for standard disclosure component
- Adde draft of do/don't and a11y documentation
=> Added default styles for Disclosure component

src/sass/footer-system/_footer-base.scss
Addresses https://app.asana.com/0/1199946964816580/1201244841384627/f
=> Changed base footer light variant link outline color to blue

src/sass/utilities/_color.scss
Fixes https://app.asana.com/0/1199946964816580/1201362600447407/f
=> Added back !important declarations to color utilities

src/js/components/tabs.js
Fixes https://app.asana.com/0/1199946964816580/1201366217856407/f
=> Fixes error thrown when no tab is initialized via attribute

src/tokens/colors.json
Fixes https://app.asana.com/0/1199946964816580/1201274780165998/f
=> Added base purple value

.github/workflows/beta.yml
See specifically lines 6 and 31.
=> Added beta release workflow

src/components/01-utilities/width.njk, src/tokens/widths.json
Added `.rvt-width-3-xl` and `.rvt-width-4-xl` utility classes to bring them into parity with spacing utilities.
=> Added new width utilities

package-lock.json, package.json, src/sass/accordion/_base.scss, src/sass/alerts/_base.scss, src/sass/buttons/_base.scss, src/sass/checkboxes/_base.scss, src/sass/dropdown/_base.scss, src/sass/file-input/_base.scss, src/sass/grid/_base.scss, src/sass/header-system/_header-lockup.scss, src/sass/header-system/_header-menu.scss, src/sass/header-system/_header-toggle-button.scss, src/sass/inputs/_base.scss, src/sass/links/_base.scss, src/sass/modals/_base.scss, src/sass/pagination/_base.scss, src/sass/quote/_base.scss, src/sass/radios/_base.scss, src/sass/sidenav/_base.scss, src/sass/step-indicator/_base.scss, src/sass/tabs/_base.scss
The `/` operator for division is deprecated.
See https://app.asana.com/0/1199946964816580/1200802859946356/f
=> Updated Sass to use math.div()

src/components/01-utilities/text.njk, src/sass/defaults/_fonts.scss, src/sass/utilities/_text.scss, src/tokens/fonts.json
This PR adds the medium weight of Benton Sans to align with updated branding guidelines.
=> Added Benton Sans Medium font-weight

package-lock.json, package.json
https://app.asana.com/0/1199946964816580/1201119412550081/f
=> Updated style-dictionary to 3.1.1

src/components/accordion/accordion.njk, src/sass/accordion/_base.scss
This PR updates the accordion component styles to be more consistent with similar styles used by the link hub component.
=> Updated accordion styles to match similar styles used by link hub

package-lock.json, package.json, src/components/accordion/accordion.njk, src/components/badge/badge.njk, src/sass/accordion/_base.scss, src/sass/badges/_base.scss, src/sass/buttons/_base.scss, src/sass/defaults/_reset.scss, src/sass/layout/_base.scss, src/sass/stat/_base.scss
Getting this open for beta.3 release tomorrow.
=> Release 2.0.0 beta.3

src/components/02-layouts/01-landing-page.njk, src/components/hero-area/hero-area.config.yml, src/components/hero-area/hero-area.njk, src/sass/buttons/_button-links.scss, src/sass/hero-area/_base.scss
This PR makes some visual design updates to help make the hero component more flexible to cover a wide amount of use cases.
- Renamed `rvt-hero__image` element to `rvt-hero__media` to be more generic about what can go inside of the hero 🚨 This will require a manual update to HTML in the 2.0.0-beta.4 release
- Rewrote CSS to allow for placement of iframes (video embeds) in addition to images in the `rvt-hero__media` element 
- Rewrote CSS to be more fluid and robust so that hero can be used with or with out images/media
- Created new `.rvt-hero--bg-dark` variant/helper class so that background color utility classes can be used to create different color variants of the hero. E.g. `<div class="rvt-hero rvt-hero--bg-dark [ rvt-bg-crimson-500 ]">...</div>`. In this case the `--bg-dark` variant …
=> Made design updates to hero component

src/components/hero-area/hero-area.config.yml, src/components/hero-area/hero-area.njk, src/sass/cta/_base.scss, src/sass/hero-area/_base.scss
Added initial support for dark background. We'll need to add and example of this to the docs in the 2.0.0-beta.4 release.
=> Added dark background hero variant

src/components/pagination/pagination.njk, src/sass/pagination/_base.scss
This is based on testing by the a11y team and implements their recommendations. It will require some small markup changes to existing implementations of the pagination component that we should note in the next release notes.
=> Made accessibility improvements to pagination component

src/sass/accordion/_base.scss, src/sass/alerts/_base.scss, src/sass/buttons/_base.scss, src/sass/checkboxes/_base.scss, src/sass/cta/_base.scss, src/sass/disclosure/_base.scss, src/sass/file-input/_base.scss, src/sass/header-system/_header-global.scss, src/sass/header-system/_header-menu.scss, src/sass/inputs/_base.scss, src/sass/links/_base.scss, src/sass/pagination/_base.scss, src/sass/sidenav/_base.scss, src/sass/stat/_base.scss, src/sass/tabs/_base.scss, src/sass/validation/_base.scss
This PR updates most component focus states including removing all box-shadow transitions.
=> Updated component focus states

src/components/_preview.njk, src/components/table/README.md, src/components/table/table.njk, src/sass/tables/_base.scss
Added a responsive table variant and draft documentation to README.md
=> Added responsive table variant

src/sass/hero-area/_base.scss
See #587 for original hero updates. This PR builds on those.
=> Fixed some hero component wrapping and layout issues

src/sass/dialog/_base.scss
This PR adds the following optional position attributes to the dialog component:
- `data-rvt-dialog-top-left`
- `data-rvt-dialog-top-right`
- `data-rvt-dialog-bottom-left`
- `data-rvt-dialog-bottom-right`
=> Added position attributes to dialog

src/js/components/dialog.js
=> Updated dialog _clickOriginatedInsideDialogOrTrigger method to use event.composedPath().some()
